#pragma once

#define MAX_FULL_MATRIX_INPUT_LEN 10
#define MAX_FULL_VECTOR_INPUT_LEN 30

typedef enum
{
    SUCCESS = 0,
    WRONG_POS_ERROR,
    NULLPTR_ERROR,
    ALLOC_ERROR,
    ELEMENT_EXIST_ERROR,
    NAN_ERROR,
    REPLACE_ERROR
} ERRORS;

typedef enum
{
    CREATE_MATRIX,
    CREATE_VECTOR,
    INPUT_MATRIX,
    INPUT_VECTOR,
    RANDOMIZE_MATRIX,
    RANDOMIZE_VECTOR,
    MULTIPLICATION_SPARSE,
    MULTIPLICATION_REGULAR,
    PRINT_MATRIX,
    PRINT_VECTOR,
    COMPARISON,
    EXIT
} OPCODES;
