#pragma once

#define MAX_SURNAME_LEN 15
#define MAX_TITLE_LEN 20
#define MAX_PUBLISHER_LEN 20
#define MAX_INDUSTRY_LEN 15

#define MAX_TYPE_WIDTH 12
#define MAX_AGE_WIDTH 7
#define MAX_GENRE_WIDTH 9
#define MAX_DOMESTIC_WIDTH 12
#define MAX_PAGES_WIDTH 5
#define MAX_YEAR_WIDTH 4

#define SUCCESS 0
#define IO_ERR 1
#define READ_ERROR 2
#define WRITE_ERROR 2

typedef enum
{
    SORT_ENTRIES,
    SORT_KEYS,
    FIND_BY_KEY,
    PRINT_ENTRIES,
    PRINT_KEYS,
    IMPORT_TABLE
} OP_CODES;
