#define MAX_MANTISSA_SIZE 40
#define MAX_EXPONENT_SIZE 5

#define SUCCESS 0
#define MEM_ALLOC_ERROR 1
#define NULLPTR_ERROR 2
#define DOUBLE_E_ERROR 3
#define DOUBLE_POINT_ERROR 4
#define INVALID_FORMAT_ERROR 5
#define CHECK_EXPONENT 6
