#pragma once

#define _GNU_SOURCE

#define MAX_MANTISSA_SIZE 40
#define MAX_EXPONENT_SIZE 5

#define SUCCESS 0
#define IO_ERR 1
#define MANTISSA_OVERFLOW 2
#define EXPONENT_OVERFLOW 3
#define EMPTY_NUMBER_ERROR 4
#define WRONG_SYMBOL_ERROR 5
#define ZERO_DIVISION 6
#define NORMALIZATION_ERROR 7
