#pragma once

#define _GNU_SOURCE

#define MAX_MANTISSA_SIZE 40
#define MAX_EXPONENT_SIZE 5

#define SUCCESS 0
#define ZERO_DIVISION 1
#define MANTISSA_OVERFLOW 2
#define IO_ERR 3
#define MANTISSA_SIGN_COUNT_ERROR 4
#define EXPONENT_SIGN_COUNT_ERROR 5
#define POINT_COUNT_ERROR 6
#define WRONG_SYMBOL_ERROR 7
#define EMPTY_NUMBER_ERROR 8
#define EXPONENT_OVERFLOW 9
