#pragma once

#define MAX_ENTRIES 500

#define MAX_SURNAME_LEN 40
#define MAX_TITLE_LEN 100
#define MAX_PUBLISHER_LEN 80
#define MAX_INDUSTRY_LEN 40

#define MAX_FILENAME_LEN 255

#define MAX_OUT_SURNAME_LEN 15
#define MAX_OUT_TITLE_LEN 36
#define MAX_OUT_PUBLISHER_LEN 10
#define MAX_OUT_PAGES_WIDTH 5
#define MAX_OUT_INDUSTRY_LEN 12
#define MAX_OUT_DOMESTIC_WIDTH 12
#define MAX_OUT_YEAR_WIDTH 4
#define MAX_OUT_TYPE_WIDTH 15
#define MAX_OUT_AGE_WIDTH 7

typedef enum
{
    SUCCESS = 0,
    NULLPTR_ERROR,
    OPEN_FILE_ERROR,
    WRONG_FILENAME_ERROR,
    WRONG_FILE_FMT_ERROR,
    READ_ERROR,
    ADD_OVERFLOW,
    NAN_ERROR,
    NOT_FOUND,
    EMPTY_TABLE
} ERRORS;

typedef enum
{
    ADD_ENTRY,
    REMOVE_ENTRY,
    FIND_BY_KEY,
    PRINT_KEY_ARRAY,
    PRINT_KEYS,
    PRINT_ENTRIES,
    BSORT_ENTRIES,
    BSORT_KEYS,
    QSORT_ENTRIES,
    QSORT_KEYS,
    IMPORT_TABLE,
    EXPORT_TABLE,
    EFFICIENCY,
    QUIT
} OPCODES;
