#pragma once

#define MAX_ENTRIES 40

#define MAX_SURNAME_LEN 15
#define MAX_TITLE_LEN 20
#define MAX_PUBLISHER_LEN 20
#define MAX_INDUSTRY_LEN 15

#define MAX_TYPE_WIDTH 12
#define MAX_AGE_WIDTH 7
#define MAX_GENRE_WIDTH 9
#define MAX_DOMESTIC_WIDTH 12
#define MAX_PAGES_WIDTH 5
#define MAX_YEAR_WIDTH 4

#define MAX_FILENAME_LEN 255

typedef enum
{
    SUCCESS = 0,
    NULLPTR_ERROR,
    OPEN_FILE_ERROR,
    WRONG_FILE_FMT_ERROR,
    READ_ERROR,
    ADD_OVERFLOW,
    NAN_ERROR,
    NOT_FOUND,
    EMPTY_TABLE
} ERRORS;

typedef enum
{
    BSORT_ENTRIES,
    BSORT_KEYS,
    QSORT_ENTRIES,
    QSORT_KEYS,
    ADD_ENTRY,
    REMOVE_ENTRY,
    FIND_BY_KEY,
    PRINT_ENTRIES,
    PRINT_KEYS,
    IMPORT_TABLE,
    EXPORT_TABLE,
    QUIT
} OPCODES;
