#pragma once

#define MAX_ENTRIES 100

#define MAX_SURNAME_LEN 40
#define MAX_TITLE_LEN 100
#define MAX_PUBLISHER_LEN 80
#define MAX_INDUSTRY_LEN 40

#define MAX_FILENAME_LEN 255

typedef enum
{
    SUCCESS = 0,
    NULLPTR_ERROR,
    OPEN_FILE_ERROR,
    WRONG_FILE_FMT_ERROR,
    READ_ERROR,
    ADD_OVERFLOW,
    NAN_ERROR,
    NOT_FOUND,
    EMPTY_TABLE
} ERRORS;

typedef enum
{
    ADD_ENTRY,
    REMOVE_ENTRY,
    FIND_BY_KEY,
    PRINT_KEY_ARRAY,
    PRINT_KEYS,
    PRINT_ENTRIES,
    BSORT_ENTRIES,
    BSORT_KEYS,
    QSORT_ENTRIES,
    QSORT_KEYS,
    IMPORT_TABLE,
    EXPORT_TABLE,
    QUIT
} OPCODES;
